apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceapp
  template:
    metadata:
      labels:
        app: serviceapp
    spec:
      containers:
        - name: serviceapp
          image: docker.io/sathishkr/serviceapp
          imagePullPolicy: Always
          ports:
            - name: svcapphttp
              containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: serviceappsvc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: serviceport
      port: 8082
      targetPort: svcapphttp
  selector:
    app: serviceapp

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: appgateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "app.digital.com"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviceappvs
spec:
  hosts:
    - "app.digital.com"
  gateways:
    - appgateway
  http:
    - match:
        - uri:
            prefix: /serviceapp
      route:
        - destination:
            port:
              number: 8082
            host: serviceappsvc
